global:
  scrape_interval:     15s
  external_labels:
    monitor: 'Monitoring-Example'

rule_files:
  - ./rules/alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    metrics_path: /metrics
    scheme: http
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
        - 'prometheus:9090'

  - job_name: 'cadvisor'
    scrape_interval: 10s
    scrape_timeout:  5s
    metrics_path: /metrics
    scheme: http
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
          - 'cadvisor:8080'
          # Add targets for cadvisor

  - job_name: 'node-exporter'
    scrape_interval: 10s
    scrape_timeout:  5s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - 'nodeexporter:9100'
          # Add targets for node exporter
